== Creating consumers
To create a consumer simply create a class that contains `@PulsarConsumer` annotation with topics list.

[source,java]
----
import io.micronaut.pulsar.annotation.PulsarSubscription;
import io.micronaut.pulsar.annotation.PulsarConsumer;

@PulsarSubscription
public class SampleListener {
    @PulsarConsumer(topics = ["persistant://public/default/test"])
    public void receive(String msg) {
        System.out.println("Received: " + msg);
    }
}
----

=== Using @PulsarSubscription annotation
This annotation servers to mark a class as a bean which should process Pulsar consumer messages. Here you can set non-required
properties `subscriptionName` which sets Pulsar consumer subscription name to custom defined string, `subscriptionType`
to one of Pulsars subscription types Exclusive, Failover, Shared, Key_Shared; and acknowledgment group timeout. If not set
they will default to Pulsar values except `subscriptionName` which is generated by this module.

|===
|Property |Type |Default |Required |Description

|subscriptionName
|java.lang.String
|
|No
|Blank string as default which will let pulsar processor generate name for it

|subscriptionType
|org.apache.pulsar.client.api.SubscriptionType
|Exclusive
|No
|Default as in Pulsar official Java library

|ackGroupTimeout
|java.lang.String
|
|No
|Must be Duration parsable string.
|===


=== Using @PulsarConsumer annotation
This is a method annotation. To use it you must specify either `String[] topics` option or `String topicsPattern`.
Topics option is parsed first so setting both values will make parser ignore topicsPattern.
|===
|Property |Type |Default |Required |Description

|topics
|java.lang.String[]
|
|Yes*
|Required unless topicsPattern is specified. Has priority over topicsPattern

|topicsPattern
|java.lang.String
|
|Yes*
|Required unless topics is specified. Regex for listening multiple topics.

|schema
|MessageSchema
|MessageSchema.BYTES or MessageSchema.JSON*
|No
|If body is different from byte[] but MessageSchema is Byte it will fallback to JSON. Currenty KEY_VALUE is not supported and will throw exception.

|consumerName
|java.lang.String
|
|No
|Consumer name, not required

|subscriptionTopicsMode
|org.apache.pulsar.client.api.RegexSubscriptionMode
|
|No
|In case topicsPattern is set this one can be one of PersistentOnly, NonPersistentOnly, AllTopics. Not required, set by
Pulsar library if not defined.

|subscribeAsync
|boolean
|true
|No
|Whether to use async when reading Pulsar messages or not.

|patternAutoDiscoveryPeriod
|int
|
|No
|Time delay in seconds after which regex subscriptions should seek new topics.

|===

TIP: When using topicsPattern be sure to create topics before consumer is started. Reason is that Pulsar refresh on new topics tends to take long time by default.

WARNING: When using PulsarConsumer with specific schema other than `byte[]` make sure topics are created and have exact same
schema as consumer is expecting. Especially when using pattern consumer which listenst to multiple topcis. Otherwise consumer
won't connect and will throw `org.apache.pulsar.client.api.PulsarClientException$IncompatibleSchemaException`.