== Creating consumers
To create a consumer annotate any bean method with a `@PulsarConsumer` and define a topic. Methods that are part of
beans annotated with a `@PulsarSubscription` will try to fetch subscription name from it. Otherwise, make sure to put
`subscriptionName` property value in the `@PulsarConsumer` annotation. Subscription beans are singletons.

snippet::example.ConsumerProducer[project-base="doc-examples/example", indent="0"]
<1> The class holding consumers can be annotated with api:pulsar.annotation.PulsarSubscription. It's also allowed to set
subscription from the `@PulsarConsumer`. By that, consumer can be located in other beans like `@Singleton`.
<2> -
<3> Methods that will process the message, in other words consumers, must be annotated with `@PulsarConsumer` and one
of the _topic_ options must be specified.
<4> Using CompletableFeature, reactor-core, RxJava return types, or Kotlin suspend, allows the body of the method to be
executed in an async manner. Method invocations will be async always as underlying Pulsar library uses CompletableFuture.
Async return type is mostly for developers control over execution flow from the method body or external callers
<5> -
<6> -
<7> -

=== Using @PulsarSubscription annotation

This annotation marks a class as a singleton bean that contains one or more methods serving as Pulsar consumers under
same subscription.

Non-required properties:

- `name`, which sets the Pulsar subscription name to a custom string; recommended to always set manually
- `type`, one of Pulsar's subscription types. Subscription types can be read in Apache Pulsar
http://pulsar.apache.org/docs/en/concepts-messaging/#subscriptions[official documentation].
- `ackGroupTimeout`, the acknowledgment group timeout for shared subscriptions

Type and acknowledgment group timeout default to Pulsar Java client library values if not set. Name will be generated
by this module in a "counter manner" (pulsar-subscription-1,2,3,4...).

|===
|Property |Type |Default |Required |Description

|name
|`java.lang.String`
|
|No
|User-specified name, or leave blank to let the Pulsar module generate the name

|type
|`org.apache.pulsar.client.api.SubscriptionType`
|`Exclusive`
|No
|Default as in Pulsar official Java library

|ackGroupTimeout
|`java.lang.String`
|
|No
|Must be a `Duration`-parsable string.
|===

=== Using @PulsarConsumer annotation

This is a method annotation. To use it you must specify one of the `value`, `topic`, `topics`, `topicsPattern`.
Properties are processed in order `topic` (alias `value`), `topics`, `topicsPattern` so setting more than one will ignore
rest depending on the order. Other properties might be omitted, however it's good to always specify consumer name manually
as it can be used later for debugging or injection points for Pulsar `Consumer<T>` which are generated for each method.

|===
|Property |Type |Default |Required |Description

|topics
|`java.lang.String[]`
|
|Yes*
|Required unless `topicsPattern` is specified. Has priority over `topicsPattern`

|topicsPattern
|`java.lang.String`
|
|Yes*
|Required unless `topics` is specified. Regex for listening to multiple topics.

|schema
|`MessageSchema`
|`MessageSchema.BYTES` or `MessageSchema.JSON`*
|No
|If body is different from `byte[]` but `MessageSchema` is `Byte`, will fallback to JSON. Currently `KEY_VALUE` is not supported and will throw an exception.

|consumerName
|`java.lang.String`
|
|No
|Consumer name, not required

|subscriptionTopicsMode
|`org.apache.pulsar.client.api.RegexSubscriptionMode`
|
|No
|If `topicsPattern` is set, this can be one of `PersistentOnly`, `NonPersistentOnly`, or `AllTopics`. Not required, set by Pulsar library if not defined.

|subscribeAsync
|`boolean`
|true
|No
|Whether to use async when reading Pulsar messages.

|patternAutoDiscoveryPeriod
|`int`
|
|No
|Time delay in seconds after which regex subscriptions should seek new topics.

|===

TIP: When using `topicsPattern`, be sure to create topics before the consumer is started, since Pulsar refresh on new
topics tends to take a long time by default.

WARNING: When using PulsarConsumer with specific schema other than `byte[]`, make sure topics are created and have the same
schema the consumer is expecting, especially when using pattern consumer which listens to multiple topics. Otherwise, the consumer
might not connect and could throw `org.apache.pulsar.client.api.PulsarClientException$IncompatibleSchemaException`.

=== Dead Letter Queue

By default Pulsar Java library does not configure DLQ to be used. Instead it will re-deliver failed messages as long as
possible which floods the consumer(s) until message if finally received. Failed means that message was received but consumer
did negative acknowledgement thus received means delivered and acknowledged by the consumer. However, reason for failure might be
bad JSON formatting (in the case where JSON is being used) or such which will create unnecessary traffic to consumer(s) and message
will never be delivered resulting in either consumers slowing down due to high redelivery count or at the end dropping
due to high load. For this purpose Micronaut Pulsar is using DLQ by default and it will retry __only__ 3 times. If you wish
to configure these options please use configuration properties `use-dead-letter-queue` and `default-max-retry-dlq`. These
properties indicate that the DLQ will be used by default on all Pulsar consumers if not explicitly set otherwise.
