== Creating consumers
To create a consumer simply create a class annotated with `@PulsarConsumer` that specifies topics.

[source,java]
----
import io.micronaut.pulsar.annotation.PulsarSubscription;
import io.micronaut.pulsar.annotation.PulsarConsumer;

@PulsarSubscription
public class SampleListener {
    @PulsarConsumer(topics = {"persistant://public/default/test"})
    public void receive(String msg) {
        System.out.println("Received: " + msg);
    }
}
----

=== Using @PulsarSubscription annotation

This annotation marks a class as a bean which will process Pulsar consumer messages. Here you can set non-required properties:

- `name`, which sets the Pulsar consumer subscription name to a custom string
- `type`, one of Pulsar's subscription types `Exclusive`, `Failover`, `Shared`, `Key_Shared`
- `ackGroupTimeout`, the acknowledgment group timeout

If not set, these default to Pulsar default values except `name` which is generated by this module.

|===
|Property |Type |Default |Required |Description

|name
|`java.lang.String`
|
|No
|User-specified name, or leave blank to let the Pulsar module generate the name

|type
|`org.apache.pulsar.client.api.SubscriptionType`
|`Exclusive`
|No
|Default as in Pulsar official Java library

|ackGroupTimeout
|`java.lang.String`
|
|No
|Must be a `Duration`-parsable string.
|===

=== Using @PulsarConsumer annotation

This is a method annotation. To use it you must specify either `String[] topics` option or `String topicsPattern`. The `topics` option is parsed first, so setting both values will cause  `topicsPattern` to be ignored.

|===
|Property |Type |Default |Required |Description

|topics
|`java.lang.String[]`
|
|Yes*
|Required unless `topicsPattern` is specified. Has priority over `topicsPattern`

|topicsPattern
|`java.lang.String`
|
|Yes*
|Required unless `topics` is specified. Regex for listening to multiple topics.

|schema
|`MessageSchema`
|`MessageSchema.BYTES` or `MessageSchema.JSON`*
|No
|If body is different from `byte[]` but `MessageSchema` is `Byte`, will fallback to JSON. Currently `KEY_VALUE` is not supported and will throw an exception.

|consumerName
|`java.lang.String`
|
|No
|Consumer name, not required

|subscriptionTopicsMode
|`org.apache.pulsar.client.api.RegexSubscriptionMode`
|
|No
|If `topicsPattern` is set, this can be one of `PersistentOnly`, `NonPersistentOnly`, or `AllTopics`. Not required, set by Pulsar library if not defined.

|subscribeAsync
|`boolean`
|true
|No
|Whether to use async when reading Pulsar messages.

|patternAutoDiscoveryPeriod
|`int`
|
|No
|Time delay in seconds after which regex subscriptions should seek new topics.

|===

TIP: When using `topicsPattern`, be sure to create topics before the consumer is started, since Pulsar refresh on new topics tends to take a long time by default.

WARNING: When using PulsarConsumer with specific schema other than `byte[]`, make sure topics are created and have the same
schema the consumer is expecting, especially when using pattern consumer which listens to multiple topics. Otherwise, the consumer
won't connect and will throw `org.apache.pulsar.client.api.PulsarClientException$IncompatibleSchemaException`.

=== Dead Letter Queue

By default Pulsar Java library does not configure DLQ to be used. Instead it will re-deliver failed messages as long as
possible which floods the consumer(s) until message if finally received. Failed means that message was received but consumer
did negative acknowledgement thus received means delivered and acknowledged by the consumer. However, reason for failure might be
bad JSON formatting (in the case where JSON is being used) or such which will create unnecessary traffic to consumer(s) and message
will never be delivered resulting in either consumers slowing down due to high redelivery count or at the end dropping
due to high load. For this purpose Micronaut Pulsar is using DLQ by default and it will retry __only__ 3 times. If you wish
to configure these options please use configuration properties `use-dead-letter-queue` and `default-max-retry-dlq`. These
properties indicate that the DLQ will be used by default on all Pulsar consumers if not explicitly set otherwise.
