== Creating producers

To initialize a producer it's sufficient to annotate an interface with `@PulsarProducerClient` and annotate methods with `@PulsarProducer`.

[source,java]
----
import io.micronaut.pulsar.annotation.PulsarProducerClient;
import io.micronaut.pulsar.annotation.PulsarProducer;

@PulsarProducerClient
public interface ProducerTester {

    @PulsarProducer(topic = "public/default/test", producerName = "test-producer")
    void producer(String message);
}
----
Only *topic* is a required parameter. Other parameters are optional. However, it's important to note that if producer name
is not set it will default to the method name, which may cause collisions in case of non-unique method names. Message content(body)
type will be determined by the first method parameter type. It will default to JSON schema if not set explicitly.

=== Producer return values

If you need the `MessageId` from Pulsar, you can
specify *MessageId* as the return type instead of *void* as given in examples below. If reactive or async return types are used,
the method can only return `MessageId` as their return type like `Maybe<MessageId>`. If you have blocking methods,
`MessageId` or the type of the parameter passed to function can be used as a return type of the method.

Examples:
[source,java]
----
import io.micronaut.pulsar.annotation.PulsarProducerClient;
import io.micronaut.pulsar.annotation.PulsarProducer;

@PulsarProducerClient
public interface ProducerTester {

    @PulsarProducer(topic = "public/default/test", producerName = "test-producer-1")
    String returnParameter(String message);

    @PulsarProducer(topic = "public/default/test", producerName = "test-producer-2")
    MessageId returnMessageId(String message);

    @PulsarProducer(topic = "public/default/test", producerName = "test-producer-3")
    Single<MessageId> returnReactive(String message);
}
----

Producers can be used as methods in other beans as well. For example: You can have a class annotated with `@PulsarSubscription`
which reads messages from one place using methods annotated with `@PulsarConsumer` and decide in that method whether to pass
on message to method annotated by the `@PulsarProducer`. This brings in flexibility to use code to decide what to send where
instead of just providing `@SentTo` or alike which sends all messages accepted by the consumer to the defined topic. It's also
useful as you can define additional logic that follows up sending or happens before it.