To configure the Apache Pulsar client, first add the `micronaut-pulsar` module dependency:

dependency:micronaut-pulsar[groupId="io.micronaut.pulsar"]

Then configure the URI of the Pulsar cluster or standalone server to communicate with:

[configuration]
.Configuring `pulsar.service-url`
----
pulsar:
  service-url: pulsar://localhost:6650
----
NOTE: As this module is based on the official Java client from Apache Pulsar, see the link:https://pulsar.apache.org/docs/en/client-libraries-java/#connection-urls[official documentation] for detailed information on service URL format.

Alternatively, `pulsar.service-url-provider` can be set using either `@kotlinexample.PulsarServiceUrlProvider` or by setting the provider name:

[configuration]
----
pulsar:
  service-url-provider: BeanName
----

in which case the implementing class must be annotated with `@Named` with value equal to the one in YAML. In both cases, the bean must implement the `org.apache.pulsar.client.api.ServiceUrlProvider` interface.

After configuring the Pulsar cluster URL, the Micronaut Pulsar module will be able to produce a bean of type `org.apache.pulsar.client.api.PulsarClient`. This bean will be a `Singleton` from which all producers and consumers can be created. Since `PulsarClient` supports an URL provider which can switch URLs to clusters on demand, there's no need to have multiple clients.
