== Readers vs Consumers
Readers can be used to gain more control over message flow. However, they are limited to single topic in contrast to consumers.
On the other hand you request each message "manually" by explicitly calling next message read. More useful feature in the  case
of Readers might be seek, where developers get the ability to position reader where they want in the message log thus being able to
manually replay messages when required. Simply put it's more similar to reading a file than reacting to an event but file gets modified by an external actor.

== Creating readers
To initialize a reader it's just declare a field annotated with `@PulsarReader` inside any bean as a field or
as an argument in its constructor.

[source,java]
----
import io.micronaut.pulsar.annotation.PulsarProducerClient;
import io.micronaut.pulsar.annotation.PulsarProducer;

@Singleton
public class MyReader {
    @PulsarReader()
    private Reader
}
----
Only *topic* is a required parameter. Other parameters are optional. However, it's important to note that if producer name is not set it will
default to method name which may cause collisions in case of same method names.

=== Producer return values
If for some reason you might need `MessageId` being returned by official Pulsar Java producer implementation you can
specify *MessageId* as return parameter instead of *void* as given in example above. If reactive or async return types are used,
method can only return MessageId as their type argument like `Maybe<MessageId>`. If you're using blocking method then
MessageId or the type of the parameter passed to function can be used as a return type of the method.

Examples:
[source,java]
----
import PulsarProducerClient;
import PulsarProducer;

@PulsarProducerClient
public interface ProducerTester {
    @PulsarProducer(topic = "public/default/test", producerName = "test-producer-1")
    String returnParameter(String message);
    @PulsarProducer(topic = "public/default/test", producerName = "test-producer-2")
    MessageId returnMessageId(String message);
    @PulsarProducer(topic = "public/default/test", producerName = "test-producer-3")
    Single<MessageId> returnReactive(String message);
}
----