plugins {
    id 'java-library'
    id 'groovy'
}

dependencies {
    api projects.micronautPulsar
    api mnTest.micronaut.test.spock
    api mn.groovy

    runtimeOnly mn.micronaut.http.server.netty
    runtimeOnly mn.micronaut.runtime

    implementation mnGrpc.micronaut.protobuff.support
    implementation mnReactor.micronaut.reactor
    implementation mnTest.micronaut.test.spock
    implementation(platform(mnTestResources.boms.testcontainers))
    implementation libs.testcontainers.pulsar
    implementation libs.conscrypt.openjdk

}

//TODO remove once Micronaut Test ships Spock version compatible with Groovy 5
configurations.all {
    resolutionStrategy {
        force("org.spockframework:spock-core:2.4-groovy-5.0")
    }
}
