micronaut:
  application:
    name: kotlin
  server:
    port: 8081
pulsar:
  enabled: true
  shutdown-on-subscriber-error: true
jackson:
  serialization:
    writeDatesAsTimestamps: false
  deserialization:
    failOnUnknownProperties: false