micronaut:
  application:
    name: kotlin
  server:
    port: 8081
pulsar:
  enabled: true
jackson:
  serialization:
    writeDatesAsTimestamps: false
  deserialization:
    failOnUnknownProperties: false