plugins {
    id 'io.micronaut.build.internal.pulsar-module'
}

dependencies {
    annotationProcessor mnValidation.micronaut.validation.processor

    implementation mnValidation.micronaut.validation

    compileOnly mnReactor.micronaut.reactor
    compileOnly mn.kotlinx.coroutines.core
    compileOnly libs.protobuf.java
    compileOnly mnGrpc.micronaut.protobuff.support

    constraints {
        implementation("org.asynchttpclient:async-http-client:3.0.7"){
            because("Older versions has a CVE(CVE-2024-53990) Vulnerability ")
        }
        implementation("com.google.code.gson:gson:2.13.2") {
            because("Older versions has a CVE(CVE-2025-53864) Vulnerability ")
        }
        implementation("com.fasterxml.jackson.core:jackson-core:2.20.1") {
            because("Older versions has a CVE(CVE-2025-52999) Vulnerability ")
        }
    }
}
